
classdef DriveControlAction < ros.Message
    %DriveControlAction MATLAB implementation of sphero_msgs/DriveControlAction
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'sphero_msgs/DriveControlAction' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '1ab3a5645cfc1af712219325819c1143' % The MD5 Checksum of the message definition
        PropertyList = { 'ActionGoal' 'ActionResult' 'ActionFeedback' } % List of non-constant message properties
        ROSPropertyList = { 'action_goal' 'action_result' 'action_feedback' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.sphero_msgs.DriveControlActionGoal' ...
            'ros.msggen.sphero_msgs.DriveControlActionResult' ...
            'ros.msggen.sphero_msgs.DriveControlActionFeedback' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        ActionGoal
        ActionResult
        ActionFeedback
    end
    methods
        function set.ActionGoal(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.sphero_msgs.DriveControlActionGoal'};
            validateattributes(val, validClasses, validAttributes, 'DriveControlAction', 'ActionGoal')
            obj.ActionGoal = val;
        end
        function set.ActionResult(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.sphero_msgs.DriveControlActionResult'};
            validateattributes(val, validClasses, validAttributes, 'DriveControlAction', 'ActionResult')
            obj.ActionResult = val;
        end
        function set.ActionFeedback(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.sphero_msgs.DriveControlActionFeedback'};
            validateattributes(val, validClasses, validAttributes, 'DriveControlAction', 'ActionFeedback')
            obj.ActionFeedback = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.sphero_msgs.DriveControlAction.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.sphero_msgs.DriveControlAction(strObj);
        end
    end
end
