title: YOUR TITLE
description: YOUR DESCRIPTION
remote_theme: just-the-docs/just-the-docs


url: https://joshfagan.github.io/sphero_toolbox

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/JoshFagan/sphero_toolbox
