## Goal: Send a drive command for the robot to execute
# Which command should be executed: Stop, DriveRawMotors, TurnAngle
string command

# Left and right speeds used in DriveRawMotors
int16 left_speed
int16 right_speed
int16 degrees
---

# Result: Success of completing the drive command
uint8 result 
---

# Feedback: Progress of completing the drive command 
uint8 feedback 
