// Generated by gencpp from file sphero_msgs/DriveControlAction.msg
// DO NOT EDIT!


#ifndef SPHERO_MSGS_MESSAGE_DRIVECONTROLACTION_H
#define SPHERO_MSGS_MESSAGE_DRIVECONTROLACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sphero_msgs/DriveControlActionGoal.h>
#include <sphero_msgs/DriveControlActionResult.h>
#include <sphero_msgs/DriveControlActionFeedback.h>

namespace sphero_msgs
{
template <class ContainerAllocator>
struct DriveControlAction_
{
  typedef DriveControlAction_<ContainerAllocator> Type;

  DriveControlAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  DriveControlAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sphero_msgs::DriveControlActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::sphero_msgs::DriveControlActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::sphero_msgs::DriveControlActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::sphero_msgs::DriveControlAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sphero_msgs::DriveControlAction_<ContainerAllocator> const> ConstPtr;

}; // struct DriveControlAction_

typedef ::sphero_msgs::DriveControlAction_<std::allocator<void> > DriveControlAction;

typedef boost::shared_ptr< ::sphero_msgs::DriveControlAction > DriveControlActionPtr;
typedef boost::shared_ptr< ::sphero_msgs::DriveControlAction const> DriveControlActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sphero_msgs::DriveControlAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sphero_msgs::DriveControlAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sphero_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sphero_msgs': ['/Users/josh/Documents/MATLAB/sphero_toolbox/custom_msgs/matlab_msg_gen_ros1/maci64/devel/share/sphero_msgs/msg'], 'actionlib_msgs': ['/Applications/MATLAB_R2021b.app/sys/ros1/maci64/ros1/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/Applications/MATLAB_R2021b.app/sys/ros1/maci64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sphero_msgs::DriveControlAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sphero_msgs::DriveControlAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sphero_msgs::DriveControlAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sphero_msgs::DriveControlAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_msgs::DriveControlAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_msgs::DriveControlAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sphero_msgs::DriveControlAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ab3a5645cfc1af712219325819c1143";
  }

  static const char* value(const ::sphero_msgs::DriveControlAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ab3a5645cfc1af7ULL;
  static const uint64_t static_value2 = 0x12219325819c1143ULL;
};

template<class ContainerAllocator>
struct DataType< ::sphero_msgs::DriveControlAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sphero_msgs/DriveControlAction";
  }

  static const char* value(const ::sphero_msgs::DriveControlAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sphero_msgs::DriveControlAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"DriveControlActionGoal action_goal\n"
"DriveControlActionResult action_result\n"
"DriveControlActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: sphero_msgs/DriveControlActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"DriveControlGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sphero_msgs/DriveControlGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"## Goal: Send a drive command for the robot to execute\n"
"# Which command should be executed: Stop, DriveRawMotors, TurnAngle\n"
"string command\n"
"\n"
"# Left and right speeds used in DriveRawMotors\n"
"int16 left_speed\n"
"int16 right_speed\n"
"int16 angle     # Angle used in turning commands\n"
"int16 heading   # Heading used in heading dependent commands\n"
"int16 time      # Time used in drive for a time amount commands\n"
"\n"
"================================================================================\n"
"MSG: sphero_msgs/DriveControlActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"DriveControlResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sphero_msgs/DriveControlResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# Result: Success of completing the drive command\n"
"uint8 result \n"
"\n"
"================================================================================\n"
"MSG: sphero_msgs/DriveControlActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"DriveControlFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: sphero_msgs/DriveControlFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# Feedback: Progress of completing the drive command \n"
"uint8 feedback \n"
"\n"
;
  }

  static const char* value(const ::sphero_msgs::DriveControlAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sphero_msgs::DriveControlAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveControlAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sphero_msgs::DriveControlAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sphero_msgs::DriveControlAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::sphero_msgs::DriveControlActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::sphero_msgs::DriveControlActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::sphero_msgs::DriveControlActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPHERO_MSGS_MESSAGE_DRIVECONTROLACTION_H
