// Generated by gencpp from file sphero_msgs/DriveControlFeedback.msg
// DO NOT EDIT!


#ifndef SPHERO_MSGS_MESSAGE_DRIVECONTROLFEEDBACK_H
#define SPHERO_MSGS_MESSAGE_DRIVECONTROLFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sphero_msgs
{
template <class ContainerAllocator>
struct DriveControlFeedback_
{
  typedef DriveControlFeedback_<ContainerAllocator> Type;

  DriveControlFeedback_()
    : feedback(0)  {
    }
  DriveControlFeedback_(const ContainerAllocator& _alloc)
    : feedback(0)  {
  (void)_alloc;
    }



   typedef uint8_t _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DriveControlFeedback_

typedef ::sphero_msgs::DriveControlFeedback_<std::allocator<void> > DriveControlFeedback;

typedef boost::shared_ptr< ::sphero_msgs::DriveControlFeedback > DriveControlFeedbackPtr;
typedef boost::shared_ptr< ::sphero_msgs::DriveControlFeedback const> DriveControlFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sphero_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sphero_msgs': ['/home/josh/GTA/sphero_toolbox/custom_msgs/matlab_msg_gen_ros1/glnxa64/devel/share/sphero_msgs/msg'], 'actionlib_msgs': ['/home/josh/Applications/R2021b/sys/ros1/glnxa64/ros1/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/home/josh/Applications/R2021b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "144732d397fbc7470829669c37fb4859";
  }

  static const char* value(const ::sphero_msgs::DriveControlFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x144732d397fbc747ULL;
  static const uint64_t static_value2 = 0x0829669c37fb4859ULL;
};

template<class ContainerAllocator>
struct DataType< ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sphero_msgs/DriveControlFeedback";
  }

  static const char* value(const ::sphero_msgs::DriveControlFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# Feedback: Progress of completing the drive command \n"
"uint8 feedback \n"
"\n"
;
  }

  static const char* value(const ::sphero_msgs::DriveControlFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveControlFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sphero_msgs::DriveControlFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sphero_msgs::DriveControlFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPHERO_MSGS_MESSAGE_DRIVECONTROLFEEDBACK_H
