
classdef DriveControlFeedback < ros.Message
    %DriveControlFeedback MATLAB implementation of sphero_msgs/DriveControlFeedback
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'sphero_msgs/DriveControlFeedback' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '144732d397fbc7470829669c37fb4859' % The MD5 Checksum of the message definition
        PropertyList = { 'Feedback' } % List of non-constant message properties
        ROSPropertyList = { 'feedback' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Feedback
    end
    methods
        function set.Feedback(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'DriveControlFeedback', 'Feedback');
            obj.Feedback = uint8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.sphero_msgs.DriveControlFeedback.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.sphero_msgs.DriveControlFeedback(strObj);
        end
    end
end
